server:
  port: 8050

app:
  name: MyApp
  description: ${app.name} serves a key role in the overall IT landscape
  url:
    #base: https://mphasisin.service-now.com/
    api: https://reqres.in/api/users/
    bankUri: https://parabank.parasoft.com/parabank/index.htm
    securityUri: http://zero.webappsecurity.com/login.html
    getUser: https://reqres.in/api/unknown/
    register: https://reqres.in/api/register


encrypted:
  username:
  password:

platform:
  #name: ios
  name: web

browser:
  name: chrome
  
parallel:
  crossbrowser: false

selenium:
  chrome.driver: library/chromedriver.exe
  gecko.driver: library/geckodriver.exe
  ie.driver: library/IEDriverServer.exe
  edge.driver: library/edge.exe

android:
  apk.file: test.apk
  #device.name=Android Emulator
  device.name: FA69W0304353
  platform.version: 10

ios:
  app.file: test.app
  device.name: 00008030-00160C803640802E
  platform.version: 13.4.1

perfecto:
  username: manoj_chavan@yahoo.com
  token: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmZjE2YTM1ZS05ZDg3LTRkMjYtOTEyYS0xZmY0MzgwM2RjNjEifQ.eyJqdGkiOiI0ZDk5M2ZlOS1iZDYxLTQzZGYtOTg5MS0yNjk0NzllNWM4ZTEiLCJleHAiOjAsIm5iZiI6MCwiaWF0IjoxNTkwNTIzMzgxLCJpc3MiOiJodHRwczovL2F1dGgtMi5hd3MtcHJvZC5wZXJmZWN0b21vYmlsZS5jb20vYXV0aC9yZWFsbXMvdGVzdGluZ2Nsb3VkLXBlcmZlY3RvbW9iaWxlLWNvbSIsImF1ZCI6Imh0dHBzOi8vYXV0aC0yLmF3cy1wcm9kLnBlcmZlY3RvbW9iaWxlLmNvbS9hdXRoL3JlYWxtcy90ZXN0aW5nY2xvdWQtcGVyZmVjdG9tb2JpbGUtY29tIiwic3ViIjoiZWYyNGRjZjAtOThhMS00Mjg3LWIzYTctMjMxMTgwZjA3Y2VkIiwidHlwIjoiT2ZmbGluZSIsImF6cCI6Im9mZmxpbmUtdG9rZW4tZ2VuZXJhdG9yIiwibm9uY2UiOiIxMzUzNWM0Yy1iYTAwLTRkNmUtOGJiNC0wYmU2MjViOTk2NjUiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiJhNDk0YzNjNy1hZWJiLTRiNTktYTQ1ZS1iNjFmODVhMmZkZjUiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIG9mZmxpbmVfYWNjZXNzIHByb2ZpbGUgZW1haWwifQ.EwcvAI6NXkkpB0AFAK3ITiRTvos9SZIPj5dK4prJh-Q
  url: https://testingcloud.perfectomobile.com/nexperience/perfectomobile/wd/hub
  #url: http://localhost:4723/wd/hub

browserstack:
  username: kanhaiya.prasad1@mphasis.com
  accessKey: JhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmZjE2YTM1ZS05ZDg3LTRkMjYtOTEyYS0xZm
  hosturl: hub-cloud.browserstack.com/wd/hub

data:
  source: json
  path: src/test/resources/inputFiles/
  
reportType:
  csv: true
  db: true
  html: true

db:
  connection:
  username:
  password:

spring:
  profiles:
    active: qa
#  data:
#    mongodb:
#      uri: mongodb+srv://lalitgarg05:LGMongo456&@cluster0.bo06j.mongodb.net/WellsFargo?retryWrites=true&w=majority
#      #host: localhost
#      #port: 27017
#      database: WellsFargo
